name: live_audio_room
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.59.5
  zego_uikit_prebuilt_live_audio_room: ^4.15.5

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatars/
    
