name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Build APK
        run: |
          cd live_audio_room
          flutter pub get
          flutter build apk --release
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: live_audio_room/build/app/outputs/flutter-apk/app-release.apk
          
